defmodule Coord.Repo.Migrations.AlignUserSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users_tokens) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:users_tokens) do
      modify :inserted_at, :utc_datetime_usec, default: nil
      modify :id, :uuid, default: nil
    end
  end
end
